/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
declare namespace Cloudflare {
	interface Env {
		EXTERNAL_DATA_MCP: DurableObjectNamespace<import("../src/index").ExternalDataMCP>;
		// External data source environment variables
		COINBASE_API_KEY?: string;
		COINBASE_API_SECRET?: string;
		CHAINLINK_API_KEY?: string;
		PYTH_API_KEY?: string;
		COINGECKO_API_KEY?: string;
		ALPHA_VANTAGE_API_KEY?: string;
	}
}

interface Env extends Cloudflare.Env {}

export { Env };